# Generated by Django 5.2.8 on 2025-11-13 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_tag_recipe_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='tag',
            new_name='tags',
        ),
    ]
