# Generated by Django 5.2.8 on 2025-11-16 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0007_ingredient_recipe_ingredient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='time_minuts',
            new_name='time_minutes',
        ),
    ]
